refactor-owner-login-screen
TheChance101/Honey-Mart-Android-Client pull request #248
Opened 2023-08-15 19:00 UTC by mahmmedn19

- refactor-login-desgin
- create usecase validation and refactor loginOwner
- handle-validation in viewModel
- add keyboard options in textFileds in email and password

2023-08-15 21:13 UTC, AmeerAmjed requested changes
Good job 👏

2023-08-15 21:13 UTC, AmeerAmjed commented on owner/src/main/java/org/the_chance/honeymart/ui/features/login/LoginViewModel.kt
This file have string hardcode can't translate.

2023-08-15 21:13 UTC, AmeerAmjed commented on owner/src/main/java/org/the_chance/honeymart/ui/features/signup/SignupScreen.kt
> +                label = stringResource(org.the_chance.design_system.R.string.continue_word),
Why change import can fix when set with import place or set with named is use another R

2023-08-17 04:34 UTC, AmeerAmjed requested changes
Issues not resolved yet.

2023-08-17 15:48 UTC, Abdelrahman-Sedky commented on owner/src/main/java/org/the_chance/honeymart/ui/features/login/LoginViewModel.kt
We need to talk about it first

2023-08-17 16:00 UTC, AmeerAmjed approved these changes
Good job👏

2023-08-17 16:14 UTC, merged