homeScreen
TheChance101/Honey-Mart-Android-Client pull request #259
Opened 2023-08-20 14:25 UTC by AbdelrahmanMohamed-m

2023-08-20 20:46 UTC, AmeerAmjed requested changes

2023-08-20 20:46 UTC, AmeerAmjed commented on core/data/src/main/java/org/the_chance/honeymart/data/repository/HoneyMartRepositoryImp.kt
> +    override suspend fun getAllUserCoupons(): List<CouponEntity> =
Don't use compact function with multi line

2023-08-20 20:46 UTC, AmeerAmjed commented on core/data/src/main/java/org/the_chance/honeymart/data/source/remote/network/HoneyMartService.kt
> +    suspend fun getAllUserCoupons(): BaseResponse<List<CouponDto>>
I don't understand what is functionally this function need improve name

2023-08-20 20:46 UTC, AmeerAmjed commented on user/src/main/java/org/the_chance/honeymart/ui/feature/bottom_navigation/BottomBarItems.kt
> +        label = "Home",
Why hardcode

2023-08-20 20:46 UTC, AmeerAmjed commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/HomeScreen.kt
>      LaunchedEffect(key1 = true) {
Should be in the end screen content

2023-08-20 20:46 UTC, AmeerAmjed commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/HomeUiState.kt
> +    val isConnectionError: Boolean = false,
Why error to specific, why not general.

2023-08-20 20:46 UTC, AmeerAmjed commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/coupon/CouponDetailsShape.kt
> +fun couponDetailsPath(size: Size, cornerRadius: Float, notchRadius: Float): Path {
Why function not private

2023-08-20 20:46 UTC, AmeerAmjed commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/coupon/CouponsItem.kt
> +fun CouponDetails(
Why multi composable in one file with multi type

2023-08-21 13:56 UTC, Eng-Light approved these changes

2023-08-21 15:47 UTC, TarekIdrees requested changes

2023-08-21 15:47 UTC, TarekIdrees commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/HomeCategoriesItem.kt
> +            .width(130.dp)
replace it with the material.dimens

2023-08-21 15:47 UTC, TarekIdrees commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/LastPurchases.kt
>              .size(width = 149.dp, height = 152.dp)
replace it with the material.dimens

2023-08-21 15:47 UTC, TarekIdrees commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/ProductItem.kt
>              .size(width = 160.dp, height = 136.dp)
replace it with the material.dimens

2023-08-21 15:47 UTC, TarekIdrees commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/ProductItem.kt
>      modifier: Modifier = Modifier,
the modifier parameter should be the first parameter with the default value, to be like this : 
isFavoriteIconClicked: Boolean,
onClickFavorite: () -> Unit,
productName: String,
productPrice: String,
modifier: Modifier = Modifier,
enable: Boolean = true,

2023-08-21 17:45 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/HomeCategoriesItem.kt
> +        /*ImageNetwork(
Left to when categories images is added

2023-08-21 19:13 UTC, AmeerAmjed approved these changes
Good job 👏😍👏.

2023-08-21 19:45 UTC, Eng-Light approved these changes

2023-08-21 20:53 UTC, merged