feature/user-notifications
TheChance101/Honey-Mart-Android-Client pull request #270
Opened 2023-08-23 14:48 UTC by MennaAkram

2023-08-23 14:53 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/feature/notifications/NotificationsScreen.kt
> +            verticalArrangement = Arrangement.spacedBy(24.dp)
material theme

2023-08-23 14:53 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/feature/notifications/NotificationsScreen.kt
> +                horizontalArrangement = Arrangement.spacedBy(32.dp),
here too

2023-08-23 14:54 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/feature/notifications/NotificationsScreen.kt
> +                        .clip(RoundedCornerShape(24.dp))
here too

2023-08-23 14:56 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/feature/notifications/NotificationsViewModel.kt
> +    private fun convertDate(date: String): String {
i dont know wich is better but i think this function should be in state not here

2023-08-23 14:56 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/feature/notifications/composable/NotificationCard.kt
> +@Composable
just put all to material theme

2023-08-23 14:59 UTC, AbdelrahmanMohamed-m commented on user/src/main/java/org/the_chance/honeymart/ui/navigation/HomeNavGraph.kt
> +        startDestination = Screen.NotificationsScreen.route,
remove this please

2023-08-23 21:05 UTC, Abdelrahman-Sedky approved these changes

2023-08-24 13:04 UTC, TarekIdrees requested changes
Is the notification sent as a flow? I mean in case the user uses the application and the notification received during the use of the application. Because I see that every function triggered from the service until the view model is used as a suspend function, not a flow.

2023-08-24 15:19 UTC, Eng-Light approved these changes

2023-08-24 15:24 UTC, TarekIdrees approved these changes

2023-08-24 15:25 UTC, merged