Refactor/pagination with out paging
TheChance101/Honey-Mart-Android-Client pull request #352
Opened 2023-09-14 15:37 UTC by MohamedElgohary88

2023-09-14 17:45 UTC, Eng-Light approved these changes

2023-09-14 19:27 UTC, IbrahimAlzaidi reviewed
Good job, if it possible then you need just to get rid of magic number which is page = 1.
better approach is to put it inside a companion object Call it maybe const val FIRSITPAGE.
other than that everything is perfect.

2023-09-15 16:46 UTC, Ethaar7 approved these changes

2023-09-17 12:42 UTC, Shehab-m requested changes
code still in progress.

2023-09-19 09:21 UTC, Shehab-m approved these changes

2023-09-19 12:29 UTC, merged